W4D2/cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

  #   Prefix Verb   URI Pattern              Controller#Action
  #     cats GET    /cats(.:format)          cats#index
  #          POST   /cats(.:format)          cats#create
  #  new_cat GET    /cats/new(.:format)      cats#new
  # edit_cat GET    /cats/:id/edit(.:format) cats#edit
  #      cat GET    /cats/:id(.:format)      cats#show
  #          PATCH  /cats/:id(.:format)      cats#update
  #          PUT    /cats/:id(.:format)      cats#update
  #          DELETE /cats/:id(.:format)      cats#destroy
end

W4D2/cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W4D2/cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  AVAILABLE_COLORS = %w(black white orange tuxedo tiger-striped calico)

  validates :birth_date, presence: true
  validate :cant_be_born_in_future
  validates :name, presence: true
  validates :color, presence: true, inclusion: { in: AVAILABLE_COLORS,
    message: '%{value} is not a valid color'}
  validates :sex, presence: true, length: { maximum: 1 }
  validates :description, presence: true

  def age
    time_ago_in_words(birth_date)
  end

  private

  def cant_be_born_in_future
    if birth_date.to_time > Time.now
      errors[:birth_date] << "can\'t be in the future!"
    end
  end
end

W4D2/cats99/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
end

W4D2/cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

W4D2/cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    if @cat.nil?
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    else
      render :show
    end
  end

  def new
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to :cats
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end

  end

  # def destroy
  #
  # end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to :cats
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

W4D2/cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

W4D2/cats99/app/helpers/cats_helper.rb
module CatsHelper
end

W4D2/cats99/app/views/cats/_form.html.erb
<!DOCTYPE html>
<html>

  <body>
    <form action= "<%= cat_url(cat) %>" method="post">
      <input type="hidden" name="_method" value="PATCH">
      <label for="cat_name">Name:</label>
      <input type="text" id="cat_name" name="cat[name]" value="<%= cat.name %>">

<br>
<br>
      <label> Sex: </label>
      <input type="radio" id='cat_sex_m' name="cat[sex]" value="M"  <%= cat.sex == "M" ? "checked" : ""  %>  >
      <label for="cat_sex_m">Male</label>
      <input type="radio" id='cat_sex_f' name="cat[sex]" value="F"  <%= cat.sex == "F" ? "checked" : ""  %> >
      <label for="cat_sex_f">Female</label>

<br>
<br>
      <label for="cat_description">Description</label>
      <textarea id="cat_description" name='cat[description]'><%= cat.description%></textarea>

<br>
<br>

      <label for="cat_color">Color</label>
      <select name="cat[color]">
        <option disabled> Color </option>
        <% colors = %w(black white orange tuxedo tiger-striped calico) %>
        <% colors.each do |color| %>
          <option value="<%=color%>"<%= cat.color == color ? 'selected' : ''  %> >
             <%= color.capitalize %>
          </option>
        <% end %>
      </select>

<br>
<br>

      <label for="cat_birth_date">Birth Date:</label>
      <input type="date" name="cat[birth_date]" value='<%= cat.birth_date %>'>

<br>
<br>

      <input type="submit" value="Rebuild my cat!">
    </form>

  </body>
</html>

W4D2/cats99/app/views/cats/edit.html.erb
<!DOCTYPE html>
<html>
<% cat = @cat %>
  <head>
    <meta charset="utf-8">
    <title>Edit Cat!</title>
  </head>
  <%= render 'form' %>
</html>

W4D2/cats99/app/views/cats/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>99 Cats</title>
  </head>
  <body>

    <h1>99 Cats</h1>

    <ul>
      <% @cats.each do |cat| %>
      <% cat_id = cat.id %>
        <li>
          <a href="/cats/<%=cat_id%> "><%= cat.name %></a>
        </li>
      <% end %>
    </ul>
  </body>
</html>

W4D2/cats99/app/views/cats/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>New Cat!</title>
  </head>
  <body>
    <form action= "<%= cats_url(@cat) %>" method="post">
      <label for="cat_name">Name:</label>
      <input type="text" id="cat_name" name="cat[name]">
      <br>
      <br>
      <label> Sex: </label>
      <input type="radio" id='cat_sex_m' name="cat[sex]" value="m">
      <label for="cat_sex_m">Male</label>
      <input type="radio" id='cat_sex_f' name="cat[sex]" value="f">
      <label for="cat_sex_f">Female</label>
      <br>
      <br>
      <label for="cat_description">Description</label>
      <textarea id="cat_description" name='cat[description]'></textarea>
      <br>
      <br>
      <label for="cat_color">Color</label>
      <select name="cat[color]">
        <option disabled> Color </option>
        <% colors = %w(black white orange tuxedo tiger-striped calico) %>
        <% colors.each do |color| %>
          <option value="<%=color%>"> <%=color.capitalize%> </option>
        <% end %>
      </select>
      <br>
      <br>
      <label for="cat_birth_date">Birth Date:</label>
      <input type="date" name="cat[birth_date]">
      <br>
      <br>
      <input type="submit" value="Build my cat!">
    </form>

  </body>
</html>

W4D2/cats99/app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> <%= @cat.name %> </title>
  </head>
  <body>
    <h1>99 Cats</h1>
    <h2><%=  @cat.name %></h2>
    <table>
      <tr>
        <td><b>Sex:</b></td>
        <td> <%= @cat.sex %> </td>
      </tr>
      <tr>
        <td><b>Age:</b></td>
        <td> <%= @cat.age.capitalize %> </td>
      </tr>
      <tr>
        <td><b>Color:</b></td>
        <td> <%= @cat.color.capitalize %> </td>
      </tr>
      <tr>
        <td><b>Description:</b></td>
        <td> <%= @cat.description %> </td>
      </tr>
    </table>

    <a href="/cats">Back to Home</a>
  </body>
</html>

W4D2/cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>