W4D5/MusicApp/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show]
  resources :bands
end

W4D5/MusicApp/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W4D5/MusicApp/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  
end

W4D5/MusicApp/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil

  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

W4D5/MusicApp/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = nil 
  end

  def logged_in?
    !session[:session_token].nil?
  end
end

W4D5/MusicApp/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    @bands = Band.new(band_params)
    if band.save
      flash[:notice] = 'Band Added!'
    else
      flash[:errors].band.errors.full_messsages
    end
  end

  def new
    @bands = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    redirect_to edit_band_url unless current_user.nil?
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if band.update_attributes(band.params)
      redirect_to band_url
    else
      flash[:error].band.errors.full_messsages
    end
  end


  def destroy
    @band = Band.find(params[:id])
      @band.destroy
  end

  private

  def

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/MusicApp/MusicApp/app/controllers/session_controller.rb
class SessionController < ApplicationController
  
end

W4D5/MusicApp/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
    params[:users][:email],
    params[:users][:password]
    )
    if user.nil?
      flash[:errors] = ['Invalid user']
      render :new
    else
      login_user!(user)
      redirect_to user_url
    end
  end

  def new
    render :new
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

W4D5/MusicApp/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if user.save
      login_user!(@user)
      flash[:notice] = 'User created.'
    else
      flash.now[:errors].user.errors.full_messsages
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

W4D5/MusicApp/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

W4D5/MusicApp/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/MusicApp/MusicApp/app/helpers/session_helper.rb
module SessionHelper
end

W4D5/MusicApp/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D5/MusicApp/MusicApp/app/helpers/user_helper.rb
module UserHelper
end

W4D5/MusicApp/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

W4D5/MusicApp/MusicApp/app/views/bands/edit.html.erb
<h1><%= @band.name %></h1>

<a>
<%= link_to "Edit #{@band.name}" %>
</a>

W4D5/MusicApp/MusicApp/app/views/bands/index.html.erb
<h1>Bands</h1>
<ul>
<%  @bands.each do |band|%>
  <li class='band_names'>
    <%=link_to "#{band.name}", band_url(band.id) %></li>
<% end %>
</ul>

W4D5/MusicApp/MusicApp/app/views/bands/show.html.erb
<p> <%= @band.name %> </h1>

<%= link_to "Edit #{@band.name}", edit_band_url(@band.id) %>

W4D5/MusicApp/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link href="https://fonts.googleapis.com/css?family=Mukta+Mahee" rel="stylesheet">
  </head>

  <body>
    <nav>
      <header>
        Music App
      </header>

      <div class="log_status">
        <% if current_user.nil?  %>
        <%= link_to 'Sign in', new_session_url %>
        <%= link_to 'Sign Up',  new_user_url %>
        <% else %>
        <%= current_user.email %>
        <%= button_to 'Log out', session_url, method: :delete %>
        <% end %>
      </div>

      <div>
        <%= link_to 'All Bands', bands_url%>
      </div>

    </nav>

    <%= yield %>
  </body>
</html>

W4D5/MusicApp/MusicApp/app/views/users/new.html.erb
<h1>Create User</h1>

<div class="input_box">

  <form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  </form>
  <label for="user_email">Email: </label>
  <input type="text" name="user[email]" id="user_email">

  <label for="user_password">Password: </label>
  <input type="password" name="user[password]" id="user_password">

  <input type="submit">


</div>